# Generated by Django 4.1.2 on 2022-10-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('buy', 'Куплено'), ('watch', 'Смотреть')], max_length=20),
        ),
    ]
