# Generated by Django 4.1.2 on 2022-10-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicroomchatmessage',
            name='content',
            field=models.TextField(),
        ),
    ]
